PACKAGE_JSON=read_json(json_path: "#{Dir.pwd}/../../package.json")
VERSION=PACKAGE_JSON[:version]
DATE=Time.new.strftime("%Y.%m%d.%H%M")

before_all do |lane, options|
  if options[:version] != ""
    VERSION=options[:version]
  end
end

default_platform(:ios)
platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Deploy a new build to TestFlight"
  lane :deploy do
    ios_set_version(xcodeproj: "SendbirdUIKitSample.xcodeproj", version: VERSION)
    ios_set_build_number(xcodeproj: "SendbirdUIKitSample.xcodeproj", build_number: DATE)
    match(type: "appstore", readonly: true, app_identifier: ["com.sendbird.uikit.reactnative.sample", "com.sendbird.uikit.reactnative.sample.NotificationService"])
    build_app(workspace: "SendbirdUIKitSample.xcworkspace", scheme: "SendbirdUIKitSample")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
